### ISSUE TITLE
Mano fits question

### ISSUE THREAD

**Issue by ZheC** [facebookresearch/ContactPose#1]
Thanks a lot for creating the dataset! One question about the mano fitting, I notice that there is only one fitting result in the json file (mano_fits_15.json) for each sequence, is this the fitting result for the first frame? Do you have the per-frame mano fitting result?

**Comment by samarth-robo** [comment]
Thanks for your interest, Zhe! The hand is static w.r.t. object in the the entire sequence, so there is only one MANO fit per sequence. If you are interested in dynamic grasps, please look at [GRAB](https://grab.is.tue.mpg.de) (synthetic data). I will release the MANO fitting code in 1-2 days in this repository.

**Comment by ZheC** [comment]
I see, make sense. Thank you for the quick response!
