### ISSUE TITLE
depth image -> point cloud

### ISSUE THREAD

**Issue by samarth-robo** [facebookresearch/ContactPose#10]
(from anonymous user via email)

Recently I have been working with your ContactPose dataset (I appreciate how thorough the analyses are in the paper!). Specifically, I have been trying to convert the provided depth images to pointclouds, but I think I am missing some information about the depth imagers.

The depth images are provided in integer format. Usually when converting images to pointclouds, we multiply values of the depth image by a scalar, which converts the integers to real-world units (meters). Looking through the annotations, I cannot find this scalar.

Do you know what the scale of the depth image is, or how I can find this out myself if I don't have access to a Kinect v2 or the .bag recordings?

**Comment by samarth-robo** [comment]
I am glad you liked ContactPose! The depth images have a 16-bit unsigned int at every pixel, which represents the depth in millimeters. You can read it with OpenCV using `im = cv2.imread(filename, -1)`, as shown in [demo.ipynb](https://github.com/facebookresearch/ContactPose/blob/master/demo.ipynb).

You will need the camera intrinsics matrix to convert this depth image to a point-cloud, one example implementation is in [`PointCloud.create_from_depth_image()`](http://www.open3d.org/docs/release/python_api/open3d.geometry.PointCloud.html#open3d.geometry.PointCloud.create_from_depth_image) from open3d.

In ContactPose, you can access the intrinsics matrix with [`ContactPose.K(camera_name)`](https://github.com/facebookresearch/ContactPose/blob/master/utilities/dataset.py#L253). However, it is slightly more complicated, because ContactPose images have been flipped and/or transposed for legacy reasons. That affine transform is given by [`ContactPose.A(camera_name)`](https://github.com/facebookresearch/ContactPose/blob/master/utilities/dataset.py#L260). So the effective intrinsics matrix is

```python
K' = np.dot(ContactPose.A(camera_name), ContactPose.K(camera_name)).
```

You would use `K'` as the intrinsics matrix in the open3d function. Extrinsics matrix is given by [`ContactPose.object_pose(camera_name, frame_idx)`](https://github.com/facebookresearch/ContactPose/blob/master/utilities/dataset.py#L276).

Finally, since the pixel values are in mm, and everything else (including the point-cloud, I assume) should be in m, the `depth_scale = 1000.0` is correct in that open3d function.

**Comment by akarshkumar0101** [comment]
If we are using a world coordinate system, should we use the wTc matrix in the annotations json?

Additionally (unrelated), this world coordinate system described by wTc and wTo, it seems the direction of gravity is -y. 
Is this exactly or approximately correct?

**Comment by samarth-robo** [comment]
@akarshkumar0101 correct, transform the point cloud by `wTc` for that camera if you want it in the world coordinate system.

About the gravity direction, what I remember is that one of the axes almost exactly pointing upwards (opposite of gravity), and the other two were parallel to the floor. So you are probably right, sorry I don't remember exactly.
