### ISSUE TITLE
Generate active area

### ISSUE THREAD

**Issue by HUSTColinLee** [facebookresearch/ContactPose#11]
Hi Everyone,

I really appreciate @samarth-robo's work of ContactPose datasets. 

I am quite interested in the Data Analysis part of the paper. I am planning to generate active area for each object as you described in this part. The goal is to generate active areas for specific hand parts. But I only find the source code of hand contact probability. Could you please give me some ideas about how to realize automatic active area discovery?

Many thanks!

**Comment by samarth-robo** [comment]
Hi @HUSTColinLee , thanks for your interest in ContactPose! I will upload the code in a day or two, and update you here.

**Comment by samarth-robo** [comment]
@HUSTColinLee sorry for the delay! Please see the latest commit 48ae33638ebd3f31de6c6cfd05304c92df8a40ba and its [documentation](https://github.com/facebookresearch/ContactPose/blob/master/docs/data_analysis.md#active-areas).
