### ISSUE TITLE
projecting 3D points to images

### ISSUE THREAD

**Issue by samarth-robo** [facebookresearch/ContactPose#13]
[from an email query]

Basically, I am trying to project the 3D vertices of objects on to provided 2D images.
I use the following transformations:
​
`projected2d_verts = (cam_intrinsics @ (cp.obj_poses[:3, :3] @ obj3d_verts.T) + cp.obj_poses[:3, 3].reshape(3,1))`

But I am getting below(wrong) projection(object projection is at the top left which should have been overlapping the mug in the hand)
​
![wrong_projection](https://user-images.githubusercontent.com/2848070/144526783-724e7a34-2525-4ceb-bdf2-9641550864e7.png)
​
I am not able to find what's wrong here. Would you have any suggestions to rectify this?
​
Thanks a lot in Advance for your time on this issue.

**Comment by samarth-robo** [comment]
Please use the `project()` function from [`utilities/misc.py`](https://github.com/facebookresearch/ContactPose/blob/main/utilities/misc.py).

An example is shown in the **Utilities** section of the [demo iPython notebook](https://github.com/facebookresearch/ContactPose/blob/main/demo.ipynb).

**Comment by anilesec** [comment]
Thank you!
