### ISSUE TITLE
Parse whole dataset

### ISSUE THREAD

**Issue by rohitdavas** [facebookresearch/ContactPose#14]
How to access whole dataset in loops ? 

We can access a single instance using ContactPose class. However, how to get exhaustive list of p_num, intent, object_name etc. which are parameters of ContactPose ? 

This is needed to convert the dataset to desired usage.

**Comment by samarth-robo** [comment]
Hi @rohitdavas, sorry for the delay in replying. You can use the `get_object_names()`, `get_intents()`, and `get_p_nums()` functions in [`utilities/dataset.py`](https://github.com/facebookresearch/ContactPose/blob/main/utilities/dataset.py).

**Comment by rohitdavas** [comment]
thanks !
