### ISSUE TITLE
Affine transformation for each cameras

### ISSUE THREAD

**Issue by anilesec** [facebookresearch/ContactPose#20]
Dear @samarth-robo ,

I understand the purpose of affine(basically to map the points in camera space to pixel space correctly). But I do not understand why each camera has different affine and why were the affines designed in the first place? 

Is it because of the way the cameras are mounted while capturing the data?

Also affine's does not have just change in axes but also shift in pixels. Could you please provide little more insight on this design?

Thank you very much!

**Comment by samarth-robo** [comment]
@anilesec this is Figure 3(a) from the [ContactPose paper](https://arxiv.org/pdf/2007.09545.pdf).

You can see for example the bottom Kinect is mounted upside down. So its affine matrix will flip it vertically.

Similarly for other Kinects as needed.

![capture_setup](https://user-images.githubusercontent.com/2848070/155026441-56ff61d9-3344-4f99-bb94-19a79f22ca51.png)
