### ISSUE TITLE
Could u provide the url of dataset?

### ISSUE THREAD

**Issue by MengHao666** [facebookresearch/ContactPose#4]
First, thanks for such great work!
I found it's not very convenient to download the dataset using the script.
Personally, it would be better if u provide the download links also.
Thanks!

**Comment by samarth-robo** [comment]
Thanks for your interest @MengHao666 ! `scripts/download_data.py` uses download links from `data/urls.json`.

**Comment by samarth-robo** [comment]
@MengHao666 if you don't mind, can you share the problems you faced while downloading with the script? That will help me improve the script.

**Comment by MengHao666** [comment]
> @MengHao666 if you don't mind, can you share the problems you faced while downloading with the script? That will help me improve the script.

Thanks for reply.
Actually, I always met 3 errors when I use your script and I don't know how to solve. This is the reason why I want to download directly,which I found is also not convenient, as in the link all the files are not in one folder or a few folders like other datasets. And I have tried at least 10 times to run the script` python startup.py` , but I can not succeed.

1. `requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /sh/l76a01eyx6sxoll/AACrvU_QYRG8A8pevM1QPCs9a?dl=1 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))`

2. `13<1:34:20, 247kiB/s]
ERROR, something went wrong
full28_use bowl Download unsuccessful
  0%|                                                                                                                                                                 | 0/1 [16:16<?, ?it/s]
`
3. `Traceback (most recent call last):
  File "startup.py", line 55, in <module>
    startup("E:/Dataset/ContactPose/")
  File "startup.py", line 45, in startup
    include_objects=('bowl',))
  File "C:\Users\mh\Desktop\ContactPose\scripts\download_data.py", line 191, in download_images
    os.symlink(src, dst)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:/Dataset/ContactPose/full28_use\\bowl\\images_full' -> 'data\\contactpose_data\\full28_use\\bowl\\images_full'`

**Comment by samarth-robo** [comment]
@MengHao666 
For 1. -- are you using a proxy? Can you report what happens when you just point your web browser (under the same proxy environment) to the URL that is causing the error `https://www.dropbox.com/sh/l76a01eyx6sxoll/AACrvU_QYRG8A8pevM1QPCs9a?dl=1`? It works fine for me without a proxy.

I will look into 3.

**Comment by MengHao666** [comment]
Thanks for generous reply!
Yep. With proxy, it works fine for me also when I directly download it using url through web browser.That is the reason why I asked for urls before. I have to use proxy.

**Comment by samarth-robo** [comment]
@MengHao666 I was able to reproduce the proxies problem.

See this [requests library documentation](https://requests.readthedocs.io/en/latest/user/advanced/#proxies). Have you set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables to your proxy server addresses? When I set them properly I was able to download using a proxy.

If you cannot set those environment variables, I also pushed commit 5bf58c1f2bbac600edb3335fb00b73d2b72f7e07, which allows you to set them in `data/proxies.json`.

**Comment by samarth-robo** [comment]
> 3. `Traceback (most recent call last):   File "startup.py", line 55, in <module> startup("E:/Dataset/ContactPose/")   File "startup.py", line 45, in startup include_objects=('bowl',))   File "C:\Users\mh\Desktop\ContactPose\scripts\download_data.py", line 191, in download_images os.symlink(src, dst) FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:/Dataset/ContactPose/full28_use\\bowl\\images_full' -> 'data\\contactpose_data\\full28_use\\bowl\\images_full'`

@MengHao666 about this error, can you re-try after deleting `data\\contactpose_data\\full28_use\\bowl\\images_full`? The code should have already caught that this directory exists, I'm not sure why it didn't.

**Comment by MengHao666** [comment]
> > 1. `Traceback (most recent call last):   File "startup.py", line 55, in <module> startup("E:/Dataset/ContactPose/")   File "startup.py", line 45, in startup include_objects=('bowl',))   File "C:\Users\mh\Desktop\ContactPose\scripts\download_data.py", line 191, in download_images os.symlink(src, dst) FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:/Dataset/ContactPose/full28_use\\bowl\\images_full' -> 'data\\contactpose_data\\full28_use\\bowl\\images_full'`
> 
> @MengHao666 about this error, can you re-try after deleting `data\\contactpose_data\\full28_use\\bowl\\images_full`? The code should have already caught that this directory exists, I'm not sure why it didn't.

Hi, thanks for advice.
However, even though I redownloaded the whole repo and deleted the whole dtaset, I still met same problem.
I retried at least 3 times and I don't know the reason.

**Comment by samarth-robo** [comment]
@MengHao666 that sounds highly unlikely. In the above error message, `E:/Dataset/ContactPose/full28_use\\bowl\\images_full -> data\\contactpose_data\\full28_use\\bowl\\images_full` means it is trying to create a symlink at `data\\contactpose_data\\full28_use\\bowl\\images_full` which points to `E:/Dataset/ContactPose/full28_use\\bowl\\images_full`. And it is complaining that `data\\contactpose_data\\full28_use\\bowl\\images_full` already exists. Which is not possible if you deleted it properly.

Please re-verify that you have deleted `data\\contactpose_data\\full28_use\\bowl\\images_full`, mention the exact command that you run when you get this error, and the whole error message. Then I can look into it further.

I cannot reproduce this issue on my end, by the way. I have run `startup.py` on multiple Ubuntu and MacOS computers, so maybe this is something Windows-specific. Looking forward to your detailed report.

**Comment by MengHao666** [comment]
> @MengHao666 that sounds highly unlikely. In the above error message, `E:/Dataset/ContactPose/full28_use\\bowl\\images_full -> data\\contactpose_data\\full28_use\\bowl\\images_full` means it is trying to create a symlink at `data\\contactpose_data\\full28_use\\bowl\\images_full` which points to `E:/Dataset/ContactPose/full28_use\\bowl\\images_full`. And it is complaining that `data\\contactpose_data\\full28_use\\bowl\\images_full` already exists. Which is not possible if you deleted it properly.
> 
> Please re-verify that you have deleted `data\\contactpose_data\\full28_use\\bowl\\images_full`, mention the exact command that you run when you get this error, and the whole error message. Then I can look into it further.
> 
> I cannot reproduce this issue on my end, by the way. I have run `startup.py` on multiple Ubuntu and MacOS computers, so maybe this is something Windows-specific. Looking forward to your detailed report.

I will try, and I did use a removable disk to download in  WIN10 system.
