### ISSUE TITLE
Joint Angles

### ISSUE THREAD

**Issue by KyraKerz** [facebookresearch/ContactPose#5]
Hello everyone,

thank you for your great work! As far as I have seen, the coordinates of the joints of the simple hands model are given as cartesian coordinates. Is there also a possibility provided to get them as joint coordinates/angles?

Thank you and best, 
Kyra

**Comment by samarth-robo** [comment]
Hi @KyraKerz, thanks for your interest in this dataset!

You could calculate the joint angles from the MANO parameters we provide. The MANO hand's full pose space has 45 dims -- 3 rotation angles for each of the 15 joints. The 45 dimensions are reduced using PCA. In ContactPose, we provide 15-dimensional pose.

So you could "unreduce" from 15 to 45 using the PCA matrix (like [this MANO code](https://github.com/hassony2/manopth/blob/master/mano/webuser/smpl_handpca_wrapper_HAND_only.py#L98) does, [PCA resource](https://stats.stackexchange.com/a/229093)), and then read off the joint angles you want.

Re: including that code in this repository, I would be happy include it if you submit a pull request!
