### ISSUE TITLE
About obtaining the key point coordinates of the hand in the camera coordinate system

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/ContactPose#8]
First, thank you for your great work!  The following is the calculation of the coordinates of the key points of the hand in the camera coordinate system. Is it correct? Do other transformations need to be done? For example, affine transformation.
`# X: Nx3 `
`P = _cTo[camera_name][frame_idx][:3]`
`X = np.vstack((X.T, np.ones(len(X))))`
`x = P @ X`
`x = x.T `

**Comment by samarth-robo** [comment]
Hi @YuyanHuang your equations correctly transform `X` from the world coordinate system to the camera coordinate system.

The affine transformation is only involved when you want to further transform the 3D points in the camera coordinate system to image pixel locations. The order is: world 3D -> camera 3D (using `cTo`) -> projection (using `K`) -> affine (using `A`) -> image.

`A = ContactPose.get_A(camera_name)` gives you the affine matrix. You should use `A` while going from 3D to 2D, and `np.linalg.inv(A)`while going from 2D to 3D.

**Comment by YuyanHuang** [comment]
@samarth-robo Yes, that's the answer I want. Thank you for your kind reply. I will close this issue.

**Comment by YuyanHuang** [comment]
After converting the object coordinates to the camera coordinate system, is the unit in meters?

**Comment by samarth-robo** [comment]
`_cTo` is in meters. So if your input `X` is in meters, the answer is yes. If your `X` is `ContactPose.hand_joints(frame_idx)`, that is in meters, yes.

**Comment by YuyanHuang** [comment]
Yes, I got it. Thank you.
